routes/web.php
<?php

use App\Http\Controllers\BuktiPembayaranController;
use App\Http\Controllers\CategoryInteriorController;
use App\Http\Controllers\DetailOrderController;
use App\Http\Controllers\InteriorGaleriController;
use App\Http\Controllers\InteriorHasProductController;
use App\Http\Controllers\KategoriProdukController;
use App\Http\Controllers\OrderFavoritesController;
use App\Http\Controllers\OrderProductController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RekeningController;
use App\Http\Controllers\StatusOrderController;
use App\Http\Controllers\WebsiteFrontEnd\WebsiteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Route::get('/', function () {
//   return view('welcome');
//});

Auth::routes(['verify' => true,
    'register' => true,
    'reset' => false,
]);

Route::get('interior_galery', function(){
    return view('website.interior_galery.index');
});

Route::get('interior_galery/detail', function(){
    return view('website.interior_galery.detail');
});
Route::get('interior_galery/detail2', function(){
    return view('website.interior_galery.detail2');
});
Route::get('interior_galery/detail3', function(){
    return view('website.interior_galery.detail3');
});
Route::get('interior_galery/detail4', function(){
    return view('website.interior_galery.detail4');
});
Route::get('interior_galery/detail5', function(){
    return view('website.interior_galery.detail5');
});

Route::get('interior_galery/detail6', function(){
    return view('website.interior_galery.detail6');
});

//Route::get('product_interior', function(){
//    return view('website.product_interior.index');
//});

Route::get('/refereshcaptcha', 'App\Http\Controllers\Auth\LoginController@refereshCaptcha');

//Custom Auth Routes
// Authentication Routes...

// Password Reset Routes...
/*$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');*/

Route::group(['middleware' => ['auth']], function () {

    Route::mediaLibrary();

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('roles', App\Http\Controllers\RoleController::class);

    Route::resource('permissions', App\Http\Controllers\PermissionController::class);

    Route::resource('users', App\Http\Controllers\UserController::class);

    Route::get('profil', [App\Http\Controllers\UserController::class, 'profil'])->name('profil');
    Route::get('editProfil/{id}', [App\Http\Controllers\UserController::class, 'editProfiles']);
    Route::patch('updateProfile/{id}', [App\Http\Controllers\UserController::class, 'updateProfile']);
    Route::resource('profiles', 'App\Http\Controllers\ProfileController');
    Route::get('editProfiles/{id}', [ProfileController::class,'editInfo']);

//
//    Route::resource('galeris', App\Http\Controllers\GaleriController::class);
//
//    Route::resource('pages', 'App\Http\Controllers\PageController');
//    Route::post('pagesIncrease/{id}', 'App\Http\Controllers\PageController@increase')->name('pagesIncrease');
//    Route::post('pagesDecrease/{id}', 'App\Http\Controllers\PageController@decrease')->name('pagesDecrease');
//
//    Route::resource('pageCategories', 'App\Http\Controllers\PageCategoryController');
//    Route::post('pageCategoriesIncrease/{id}', 'App\Http\Controllers\PageCategoryController@increase')->name('pageCategoriesIncrease');
//    Route::post('pageCategoriesDecrease/{id}', 'App\Http\Controllers\PageCategoryController@decrease')->name('pageCategoriesDecrease');
//
//    Route::resource('posts', 'App\Http\Controllers\PostController');
//
//    Route::resource('postCategories', 'App\Http\Controllers\PostCategoryController');
//    Route::post('postCategoriesIncrease/{id}', 'App\Http\Controllers\PostCategoryController@increase')->name('postCategoriesIncrease');
//    Route::post('postCategoriesDecrease/{id}', 'App\Http\Controllers\PostCategoryController@decrease')->name('postCategoriesDecrease');
    Route::resource('interiorGaleris', InteriorGaleriController::class);
    Route::resource('categoryInteriors', CategoryInteriorController::class);
    Route::resource('kategoriProduks', KategoriProdukController::class);
    Route::resource('produks', ProdukController::class);
    Route::post('produks_modal', [ProdukController::class, 'storeModal'])->name('produks_modal');
    Route::resource('interiorHasProducts', InteriorHasProductController::class);

    Route::resource('statusOrders', StatusOrderController::class);
    Route::resource('orderProducts', OrderProductController::class);
    Route::put('postOrder/{orderId}', [OrderProductController::class,'postOrder']);
    Route::get('updateStatus/{idOrder}', [OrderProductController::class,'updateStatus']);
    Route::resource('detailOrders', DetailOrderController::class);
    Route::resource('orderFavorites', OrderFavoritesController::class);
    Route::get('favoritesAdd/{interiorId}', [OrderFavoritesController::class,'favoriteAdd']);
    Route::get('order/{productId}', [OrderProductController::class,'insertOrder']);
    Route::resource('rekenings', RekeningController::class);
    Route::resource('buktiPembayarans', BuktiPembayaranController::class);
});

//----WEBSITE FRONT END
//Route::get('/', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'index'])->name('beranda');
//
////Detail Post
Route::get('post/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailPost'])->name('detail-post');
Route::get('page/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailPage'])->name('detail-page');
//
////Post Category
//Route::get('category/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'listPostByCategory'])->name('category-post');
//Route::get('sejarah', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'profilSejarah']);
//Route::get('profil-anggota-dprd', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'profilAnggotaDprd']);
//Route::get('post-utama', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'beritaUtama']);
//Route::get('post-utama/indeks', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'beritaSearch']);
//Route::get('anggota-dewan', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'anggotaDewan']);
//Route::get('alat-kelengkapan-dewan/{slugAkdCategory}', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'akdListPerson'])->name('alat-kelengkapan-dewan');
//Route::get('semua-anggota-dewan', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'listPersonDewan'])->name('semua-anggota-dewan');
//Route::get('semua-anggota-sekretariat', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'listPersonSekretariat'])->name('semua-anggota-sekretariat');
//Route::get('galeri-foto', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'galeriFoto'])->name('galeri-foto');
//Route::get('galeri-foto/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailGaleriFoto'])->name('detail-galeri-foto');
//Route::get('detail-person-dewan/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'detailPersonDewan'])->name('detail-person-dewan');
//Route::get('detail-person-sekretariat/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'detailPersonSekretariat'])->name('detail-person-sekretariat');
//Route::get('detail-instagram/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailInstagram'])->name('detail-instagram');
//Route::get('agenda-dprd', [WebsiteController::class,'agendaDprd'])->name('agenda-dprd');
//Route::get('agenda/agenda-detail/{slug}', [WebsiteController::class,'detailAgenda'])->name('agenda-detail');

Route::get('/',[WebsiteController::class,'index'])->name('beranda');
Route::get('interior',[WebsiteController::class,'interiorGaleri'])->name("interior-galeri");
Route::get('interior/{slug}',[WebsiteController::class,'detailInterior'])->name("interior-detail");
Route::get('product',[WebsiteController::class,'product'])->name('product-interior');
Route::get('checkout', [WebsiteController::class,'checkout']);
Route::get('orderStatus', [WebsiteController::class,'statusOrder'])->name('order_status');
Route::get('favorite', [WebsiteController::class,'favoriteInterior'])->name('favorite');

app/Models/BuktiPembayaran.php
<?php

namespace App\Models;

use CyrildeWit\EloquentViewable\Contracts\Viewable;
use CyrildeWit\EloquentViewable\InteractsWithViews;
use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\Image\Manipulations;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

/**
 * Class BuktiPembayaran
 * @package App\Models
 * @version August 15, 2022, 12:12 pm UTC
 *
 * @property \App\Models\OrderProduct $orderProduct
 * @property string $deskripsi
 * @property integer $order_product_id
 */
class BuktiPembayaran extends Model implements HasMedia,Viewable
{
    use SoftDeletes;

    use HasFactory;
    use InteractsWithMedia;
    use InteractsWithViews;

    public $table = 'bukti_pembayaran';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];

    public function registerMediaConversions(Media $media = null): void
    {
        $this
            ->addMediaConversion('preview')
            ->fit(Manipulations::FIT_CROP, 300, 300)
            ->nonQueued();

        $this->addMediaConversion('thumb')
            ->width(368)
            ->height(232)
            ->sharpen(10);

        $this->addMediaConversion('cover')
            ->width(2400)
            ->height(1800);
    }


    public $fillable = [
        'deskripsi',
        'order_product_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'deskripsi' => 'string',
        'order_product_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'deskripsi' => 'nullable|string|max:255',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable',
        'order_product_id' => 'required|integer'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function orderProduct()
    {
        return $this->belongsTo(\App\Models\OrderProduct::class, 'order_product_id');
    }
}

app/Http/Controllers/BuktiPembayaranController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateBuktiPembayaranRequest;
use App\Http\Requests\UpdateBuktiPembayaranRequest;
use App\Models\OrderProduct;
use App\Models\StatusOrder;
use App\Repositories\BuktiPembayaranRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class BuktiPembayaranController extends AppBaseController
{
    /** @var  BuktiPembayaranRepository */
    private $buktiPembayaranRepository;

    public function __construct(BuktiPembayaranRepository $buktiPembayaranRepo)
    {
        $this->buktiPembayaranRepository = $buktiPembayaranRepo;
    }

    /**
     * Display a listing of the BuktiPembayaran.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $buktiPembayarans = $this->buktiPembayaranRepository->all();

        return view('bukti_pembayarans.index')
            ->with('buktiPembayarans', $buktiPembayarans);
    }

    /**
     * Show the form for creating a new BuktiPembayaran.
     *
     * @return Response
     */
    public function create()
    {
        return view('bukti_pembayarans.create');
    }

    /**
     * Store a newly created BuktiPembayaran in storage.
     *
     * @param CreateBuktiPembayaranRequest $request
     *
     * @return Response
     */
    public function store(CreateBuktiPembayaranRequest $request)
    {
        $status = StatusOrder::where('name','like','%PROSES%')->first();
        $input = $request->all();

        $buktiPembayaran = $this->buktiPembayaranRepository->create($input);

        $buktiPembayaran->addFromMediaLibraryRequest($request->media)
            ->toMediaCollection();

        $order = OrderProduct::find($buktiPembayaran->order_product_id);
        $order['note_order'] = "Verifikasi Pembayaran";
        $order['status_id'] = $status->id;
        $order->update();

        Flash::success('Bukti Pembayaran saved successfully.');

        return redirect(url('orderStatus'));
    }

    /**
     * Display the specified BuktiPembayaran.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $buktiPembayaran = $this->buktiPembayaranRepository->find($id);

        if (empty($buktiPembayaran)) {
            Flash::error('Bukti Pembayaran not found');

            return redirect(route('buktiPembayarans.index'));
        }

        return view('bukti_pembayarans.show')->with('buktiPembayaran', $buktiPembayaran);
    }

    /**
     * Show the form for editing the specified BuktiPembayaran.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $buktiPembayaran = $this->buktiPembayaranRepository->find($id);

        if (empty($buktiPembayaran)) {
            Flash::error('Bukti Pembayaran not found');

            return redirect(route('buktiPembayarans.index'));
        }

        return view('bukti_pembayarans.edit')->with('buktiPembayaran', $buktiPembayaran);
    }

    /**
     * Update the specified BuktiPembayaran in storage.
     *
     * @param int $id
     * @param UpdateBuktiPembayaranRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateBuktiPembayaranRequest $request)
    {
        $buktiPembayaran = $this->buktiPembayaranRepository->find($id);

        if (empty($buktiPembayaran)) {
            Flash::error('Bukti Pembayaran not found');

            return redirect(route('buktiPembayarans.index'));
        }

        $buktiPembayaran = $this->buktiPembayaranRepository->update($request->all(), $id);

        Flash::success('Bukti Pembayaran updated successfully.');

        return redirect(route('buktiPembayarans.index'));
    }

    /**
     * Remove the specified BuktiPembayaran from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $buktiPembayaran = $this->buktiPembayaranRepository->find($id);

        if (empty($buktiPembayaran)) {
            Flash::error('Bukti Pembayaran not found');

            return redirect(route('buktiPembayarans.index'));
        }

        $this->buktiPembayaranRepository->delete($id);

        Flash::success('Bukti Pembayaran deleted successfully.');

        return redirect(route('buktiPembayarans.index'));
    }
}

resources/views/bukti_pembayarans/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-green p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="green font-medium-5">Input Bukti Pembayaran</span><br>
                                    <span style="margin-top: -5px">Membuat Bukti Pembayaran Baru</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                {!! Form::open(['route' => 'buktiPembayarans.store'], ['class' => 'form']) !!}
                                <div class="form-body">
                                    @include('bukti_pembayarans.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/bukti_pembayarans/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-indigo p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="indigo font-medium-5">Perubahan Bukti Pembayaran</span><br>
                                    <span style="margin-top: -5px">Melakukan Perubahan Bukti Pembayaran </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                {!! Form::model($buktiPembayaran, ['route' => ['buktiPembayarans.update', $buktiPembayaran->id], 'method' => 'patch']) !!}
                                <div class="form-body">
                                    @include('bukti_pembayarans.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/bukti_pembayarans/fields.blade.php
<!-- Deskripsi Field -->
<div class="form-group">
    {!! Form::label('deskripsi', 'Deskripsi:') !!}
    <div class="position-relative">
        {!! Form::text('deskripsi', null, ['class' => 'form-control']) !!}
    </div>
</div>


<!-- Order Product Id Field -->
<div class="form-group">
    {!! Form::label('order_product_id', 'Order Product Id:') !!}
    <div class="position-relative">
        {!! Form::number('order_product_id', null, ['class' => 'form-control']) !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Submit Field -->
<div class="form-actions center">
    <a href="{!! route('buktiPembayarans.index') !!}" class="btn btn-danger"> <i class="fa fa-close"></i> Batal</a>
    {!! Form::submit('Simpan', ['class' => 'btn btn-green mr-1']) !!}
</div>

resources/views/bukti_pembayarans/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                @include('flash::message')
                <div class="clearfix"></div>
                <div class="card">
                    <div class="border-left-pink border-left-6 box-shadow-1 rounded">
                        <div class="card-content ">
                            <div class="card-body card-dashboard">
                                <div class="row">
                                    <div class="col-10 media-body mb-2">
                                        <div class="content-header-left breadcrumb-new">
                                            <span class="content-header-title mb-0 d-inline-block font-medium-4"><b>Bukti Pembayarans</b></span>
                                            <div class="breadcrumbs-top d-inline-block">
                                                <div class="breadcrumb-wrapper">
                                                    @include('layouts.breadcrumb')
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-2 text-right">
                                        <a href="{!! route('buktiPembayarans.create') !!}" class="btn btn-sm btn-green">Tambah Data</a>
                                    </div>
                                </div>
                                @include('bukti_pembayarans.table')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bukti_pembayarans/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-blue p-2 media-middle">
                                    <i class="fa fa-align-left font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="blue font-medium-5"> Bukti Pembayaran</span><br>
                                    <span style="margin-top: -5px">Detail Bukti Pembayaran</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form class="form form-horizontal">
                                    <div class="form-body">
                                        <h4 class="form-section">
                                            <a href="{!! route('buktiPembayarans.index') !!}" class="btn btn-icon danger btn-lg pl-0 ml-0"><i class="ft-arrow-left"></i> Kembali</a>
                                        </h4>
                                        @include('bukti_pembayarans.show_fields')
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/bukti_pembayarans/show_fields.blade.php
<!-- Sudah di modifikasi -->
<!-- Deskripsi Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('deskripsi', 'Deskripsi:') !!}
        </h5>
        {!! $buktiPembayaran->deskripsi !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Order Product Id Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('order_product_id', 'Order Product Id:') !!}
        </h5>
        {!! $buktiPembayaran->order_product_id !!}
    </div>
</div>

resources/views/bukti_pembayarans/table.blade.php
<!-- Sudah di modifikasi untuk Edit,Lihat,Hapus -->
<table class="table table-hover table-bordered table-striped default table-responsive">
    <colgroup>
        <col class="col-xs-1">
        <col class="col-xs-7">
    </colgroup>
    <thead>
    <tr>
        <th><code>#</code></th>
        <th>Deskripsi</th>
        <th>Order Product Id</th>
        <th style="text-align: center">Action</th>
    </tr>
    </thead>
    <tbody>
    @php
        $no = 1;
    @endphp
    @foreach($buktiPembayarans as $buktiPembayaran)
        <tr>
            <td>{!! $no++ !!}</td>
            <td>{!! $buktiPembayaran->deskripsi !!}</td>
            <td>{!! $buktiPembayaran->order_product_id !!}</td>
            <td>
                {!! Form::open(['route' => ['buktiPembayarans.destroy', $buktiPembayaran->id], 'method' => 'delete']) !!}
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{!! route('buktiPembayarans.show', [$buktiPembayaran->id]) !!}" class="btn btn-sm btn-success"><i class="fa fa-eye"></i></a>
                                       <a href="{!! route('buktiPembayarans.edit', [$buktiPembayaran->id]) !!}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                                       {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>