routes/web.php
<?php

use App\Http\Controllers\BuktiPembayaranController;
use App\Http\Controllers\CategoryInteriorController;
use App\Http\Controllers\DetailOrderController;
use App\Http\Controllers\InteriorGaleriController;
use App\Http\Controllers\InteriorHasProductController;
use App\Http\Controllers\KategoriProdukController;
use App\Http\Controllers\OrderFavoritesController;
use App\Http\Controllers\OrderProductController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RekeningController;
use App\Http\Controllers\StatusOrderController;
use App\Http\Controllers\WebsiteFrontEnd\WebsiteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Route::get('/', function () {
//   return view('welcome');
//});

Auth::routes(['verify' => true,
    'register' => true,
    'reset' => false,
]);

Route::get('interior_galery', function(){
    return view('website.interior_galery.index');
});

Route::get('interior_galery/detail', function(){
    return view('website.interior_galery.detail');
});
Route::get('interior_galery/detail2', function(){
    return view('website.interior_galery.detail2');
});
Route::get('interior_galery/detail3', function(){
    return view('website.interior_galery.detail3');
});
Route::get('interior_galery/detail4', function(){
    return view('website.interior_galery.detail4');
});
Route::get('interior_galery/detail5', function(){
    return view('website.interior_galery.detail5');
});

Route::get('interior_galery/detail6', function(){
    return view('website.interior_galery.detail6');
});

//Route::get('product_interior', function(){
//    return view('website.product_interior.index');
//});

Route::get('/refereshcaptcha', 'App\Http\Controllers\Auth\LoginController@refereshCaptcha');

//Custom Auth Routes
// Authentication Routes...

// Password Reset Routes...
/*$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');*/

Route::group(['middleware' => ['auth']], function () {

    Route::mediaLibrary();

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('roles', App\Http\Controllers\RoleController::class);

    Route::resource('permissions', App\Http\Controllers\PermissionController::class);

    Route::resource('users', App\Http\Controllers\UserController::class);

    Route::get('profil', [App\Http\Controllers\UserController::class, 'profil'])->name('profil');
    Route::get('editProfil/{id}', [App\Http\Controllers\UserController::class, 'editProfiles']);
    Route::patch('updateProfile/{id}', [App\Http\Controllers\UserController::class, 'updateProfile']);
    Route::resource('profiles', 'App\Http\Controllers\ProfileController');
    Route::get('editProfiles/{id}', [ProfileController::class,'editInfo']);

//
//    Route::resource('galeris', App\Http\Controllers\GaleriController::class);
//
//    Route::resource('pages', 'App\Http\Controllers\PageController');
//    Route::post('pagesIncrease/{id}', 'App\Http\Controllers\PageController@increase')->name('pagesIncrease');
//    Route::post('pagesDecrease/{id}', 'App\Http\Controllers\PageController@decrease')->name('pagesDecrease');
//
//    Route::resource('pageCategories', 'App\Http\Controllers\PageCategoryController');
//    Route::post('pageCategoriesIncrease/{id}', 'App\Http\Controllers\PageCategoryController@increase')->name('pageCategoriesIncrease');
//    Route::post('pageCategoriesDecrease/{id}', 'App\Http\Controllers\PageCategoryController@decrease')->name('pageCategoriesDecrease');
//
//    Route::resource('posts', 'App\Http\Controllers\PostController');
//
//    Route::resource('postCategories', 'App\Http\Controllers\PostCategoryController');
//    Route::post('postCategoriesIncrease/{id}', 'App\Http\Controllers\PostCategoryController@increase')->name('postCategoriesIncrease');
//    Route::post('postCategoriesDecrease/{id}', 'App\Http\Controllers\PostCategoryController@decrease')->name('postCategoriesDecrease');
    Route::resource('interiorGaleris', InteriorGaleriController::class);
    Route::resource('categoryInteriors', CategoryInteriorController::class);
    Route::resource('kategoriProduks', KategoriProdukController::class);
    Route::resource('produks', ProdukController::class);
    Route::post('produks_modal', [ProdukController::class, 'storeModal'])->name('produks_modal');
    Route::resource('interiorHasProducts', InteriorHasProductController::class);

    Route::resource('statusOrders', StatusOrderController::class);
    Route::resource('orderProducts', OrderProductController::class);
    Route::put('postOrder/{orderId}', [OrderProductController::class,'postOrder']);
    Route::get('updateStatus/{idOrder}', [OrderProductController::class,'updateStatus']);
    Route::resource('detailOrders', DetailOrderController::class);
    Route::resource('orderFavorites', OrderFavoritesController::class);
    Route::get('favoritesAdd/{interiorId}', [OrderFavoritesController::class,'favoriteAdd']);
    Route::get('order/{productId}', [OrderProductController::class,'insertOrder']);
    Route::resource('rekenings', RekeningController::class);
    Route::resource('buktiPembayarans', BuktiPembayaranController::class);
});

//----WEBSITE FRONT END
//Route::get('/', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'index'])->name('beranda');
//
////Detail Post
Route::get('post/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailPost'])->name('detail-post');
Route::get('page/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailPage'])->name('detail-page');
//
////Post Category
//Route::get('category/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'listPostByCategory'])->name('category-post');
//Route::get('sejarah', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'profilSejarah']);
//Route::get('profil-anggota-dprd', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'profilAnggotaDprd']);
//Route::get('post-utama', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'beritaUtama']);
//Route::get('post-utama/indeks', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'beritaSearch']);
//Route::get('anggota-dewan', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'anggotaDewan']);
//Route::get('alat-kelengkapan-dewan/{slugAkdCategory}', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'akdListPerson'])->name('alat-kelengkapan-dewan');
//Route::get('semua-anggota-dewan', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'listPersonDewan'])->name('semua-anggota-dewan');
//Route::get('semua-anggota-sekretariat', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'listPersonSekretariat'])->name('semua-anggota-sekretariat');
//Route::get('galeri-foto', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'galeriFoto'])->name('galeri-foto');
//Route::get('galeri-foto/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailGaleriFoto'])->name('detail-galeri-foto');
//Route::get('detail-person-dewan/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'detailPersonDewan'])->name('detail-person-dewan');
//Route::get('detail-person-sekretariat/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'detailPersonSekretariat'])->name('detail-person-sekretariat');
//Route::get('detail-instagram/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailInstagram'])->name('detail-instagram');
//Route::get('agenda-dprd', [WebsiteController::class,'agendaDprd'])->name('agenda-dprd');
//Route::get('agenda/agenda-detail/{slug}', [WebsiteController::class,'detailAgenda'])->name('agenda-detail');

Route::get('/',[WebsiteController::class,'index'])->name('beranda');
Route::get('interior',[WebsiteController::class,'interiorGaleri'])->name("interior-galeri");
Route::get('interior/{slug}',[WebsiteController::class,'detailInterior'])->name("interior-detail");
Route::get('product',[WebsiteController::class,'product'])->name('product-interior');
Route::get('checkout', [WebsiteController::class,'checkout']);
Route::get('orderStatus', [WebsiteController::class,'statusOrder'])->name('order_status');
Route::get('favorite', [WebsiteController::class,'favoriteInterior'])->name('favorite');

app/Models/CategoryInterior.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

/**
 * Class CategoryInterior
 * @package App\Models
 * @version June 11, 2022, 3:14 am UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection $interiors
 * @property string $title
 * @property string $title_eng
 * @property string $description
 * @property string $description_eng
 * @property string $slug
 */
class CategoryInterior extends Model
{
    use SoftDeletes;
    use HasSlug;

    use HasFactory;

    public $table = 'category_interior';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'title',
        'title_eng',
        'description',
        'description_eng',
        'slug'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'title' => 'string',
        'title_eng' => 'string',
        'description' => 'string',
        'description_eng' => 'string',
        'slug' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'title' => 'nullable|string|max:255',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug')->doNotGenerateSlugsOnUpdate();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function interiors()
    {
        return $this->hasMany(\App\Models\Interior::class, 'category_interior_id');
    }
}

app/Http/Controllers/CategoryInteriorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCategoryInteriorRequest;
use App\Http\Requests\UpdateCategoryInteriorRequest;
use App\Repositories\CategoryInteriorRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class CategoryInteriorController extends AppBaseController
{
    /** @var  CategoryInteriorRepository */
    private $categoryInteriorRepository;

    public function __construct(CategoryInteriorRepository $categoryInteriorRepo)
    {
        $this->categoryInteriorRepository = $categoryInteriorRepo;
    }

    /**
     * Display a listing of the CategoryInterior.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $categoryInteriors = $this->categoryInteriorRepository->all();

        return view('category_interiors.index')
            ->with('categoryInteriors', $categoryInteriors);
    }

    /**
     * Show the form for creating a new CategoryInterior.
     *
     * @return Response
     */
    public function create()
    {
        return view('category_interiors.create');
    }

    /**
     * Store a newly created CategoryInterior in storage.
     *
     * @param CreateCategoryInteriorRequest $request
     *
     * @return Response
     */
    public function store(CreateCategoryInteriorRequest $request)
    {
        $input = $request->all();

        $categoryInterior = $this->categoryInteriorRepository->create($input);

        Flash::success('Category Interior saved successfully.');

        return redirect(route('categoryInteriors.index'));
    }

    /**
     * Display the specified CategoryInterior.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $categoryInterior = $this->categoryInteriorRepository->find($id);

        if (empty($categoryInterior)) {
            Flash::error('Category Interior not found');

            return redirect(route('categoryInteriors.index'));
        }

        return view('category_interiors.show')->with('categoryInterior', $categoryInterior);
    }

    /**
     * Show the form for editing the specified CategoryInterior.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $categoryInterior = $this->categoryInteriorRepository->find($id);

        if (empty($categoryInterior)) {
            Flash::error('Category Interior not found');

            return redirect(route('categoryInteriors.index'));
        }

        return view('category_interiors.edit')->with('categoryInterior', $categoryInterior);
    }

    /**
     * Update the specified CategoryInterior in storage.
     *
     * @param int $id
     * @param UpdateCategoryInteriorRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCategoryInteriorRequest $request)
    {
        $categoryInterior = $this->categoryInteriorRepository->find($id);

        if (empty($categoryInterior)) {
            Flash::error('Category Interior not found');

            return redirect(route('categoryInteriors.index'));
        }

        $categoryInterior = $this->categoryInteriorRepository->update($request->all(), $id);

        Flash::success('Category Interior updated successfully.');

        return redirect(route('categoryInteriors.index'));
    }

    /**
     * Remove the specified CategoryInterior from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $categoryInterior = $this->categoryInteriorRepository->find($id);

        if (empty($categoryInterior)) {
            Flash::error('Category Interior not found');

            return redirect(route('categoryInteriors.index'));
        }

        $this->categoryInteriorRepository->delete($id);

        Flash::success('Category Interior deleted successfully.');

        return redirect(route('categoryInteriors.index'));
    }
}

resources/views/category_interiors/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-green p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="green font-medium-5">Input Category Interior</span><br>
                                    <span style="margin-top: -5px">Membuat Category Interior Baru</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                {!! Form::open(['route' => 'categoryInteriors.store'], ['class' => 'form']) !!}
                                <div class="form-body">
                                    @include('category_interiors.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/category_interiors/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-indigo p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="indigo font-medium-5">Perubahan Category Interior</span><br>
                                    <span style="margin-top: -5px">Melakukan Perubahan Category Interior </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                {!! Form::model($categoryInterior, ['route' => ['categoryInteriors.update', $categoryInterior->id], 'method' => 'patch']) !!}
                                <div class="form-body">
                                    @include('category_interiors.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/category_interiors/fields.blade.php
<!-- Title Field -->
<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    <div class="position-relative">
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>
</div>


{{--<!-- Title Eng Field -->--}}
{{--<div class="form-group">--}}
{{--    {!! Form::label('title_eng', 'Title Eng:') !!}--}}
{{--    <div class="position-relative">--}}
{{--        {!! Form::text('title_eng', null, ['class' => 'form-control']) !!}--}}
{{--    </div>--}}
{{--</div>--}}


<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <div class="position-relative">
        {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
    </div>
</div>


{{--<!-- Description Eng Field -->--}}
{{--<div class="form-group">--}}
{{--    {!! Form::label('description_eng', 'Description Eng:') !!}--}}
{{--    <div class="position-relative">--}}
{{--        {!! Form::textarea('description_eng', null, ['class' => 'form-control']) !!}--}}
{{--    </div>--}}
{{--</div>--}}


<!-- Sudah di modifikasi -->
<!-- Submit Field -->
<div class="form-actions center">
    <a href="{!! route('categoryInteriors.index') !!}" class="btn btn-danger"> <i class="fa fa-close"></i> Batal</a>
    {!! Form::submit('Simpan', ['class' => 'btn btn-green mr-1']) !!}
</div>

resources/views/category_interiors/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                @include('flash::message')
                <div class="clearfix"></div>
                <div class="card">
                    <div class="border-left-pink border-left-6 box-shadow-1 rounded">
                        <div class="card-content ">
                            <div class="card-body card-dashboard">
                                <div class="row">
                                    <div class="col-10 media-body mb-2">
                                        <div class="content-header-left breadcrumb-new">
                                            <span class="content-header-title mb-0 d-inline-block font-medium-4"><b>Category Interiors</b></span>
                                            <div class="breadcrumbs-top d-inline-block">
                                                <div class="breadcrumb-wrapper">
                                                    @include('layouts.breadcrumb')
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-2 text-right">
                                        <a href="{!! route('categoryInteriors.create') !!}" class="btn btn-sm btn-green">Tambah Data</a>
                                    </div>
                                </div>
                                @include('category_interiors.table')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category_interiors/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-blue p-2 media-middle">
                                    <i class="fa fa-align-left font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="blue font-medium-5"> Category Interior</span><br>
                                    <span style="margin-top: -5px">Detail Category Interior</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form class="form form-horizontal">
                                    <div class="form-body">
                                        <h4 class="form-section">
                                            <a href="{!! route('categoryInteriors.index') !!}" class="btn btn-icon danger btn-lg pl-0 ml-0"><i class="ft-arrow-left"></i> Kembali</a>
                                        </h4>
                                        @include('category_interiors.show_fields')
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/category_interiors/show_fields.blade.php
<!-- Sudah di modifikasi -->
<!-- Title Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('title', 'Title:') !!}
        </h5>
        {!! $categoryInterior->title !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Title Eng Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('title_eng', 'Title Eng:') !!}
        </h5>
        {!! $categoryInterior->title_eng !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Description Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('description', 'Description:') !!}
        </h5>
        {!! $categoryInterior->description !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Description Eng Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('description_eng', 'Description Eng:') !!}
        </h5>
        {!! $categoryInterior->description_eng !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Slug Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('slug', 'Slug:') !!}
        </h5>
        {!! $categoryInterior->slug !!}
    </div>
</div>

resources/views/category_interiors/table.blade.php
<!-- Sudah di modifikasi untuk Edit,Lihat,Hapus -->
<table class="table table-hover table-bordered table-striped default table-responsive">
    <colgroup>
        <col class="col-xs-1">
        <col class="col-xs-7">
    </colgroup>
    <thead>
    <tr>
        <th><code>#</code></th>
        <th>Title</th>
        <th>Title Eng</th>
        <th>Description</th>
        <th>Description Eng</th>
        <th>Slug</th>
        <th style="text-align: center">Action</th>
    </tr>
    </thead>
    <tbody>
    @php
        $no = 1;
    @endphp
    @foreach($categoryInteriors as $categoryInterior)
        <tr>
            <td>{!! $no++ !!}</td>
            <td>{!! $categoryInterior->title !!}</td>
            <td>{!! $categoryInterior->title_eng !!}</td>
            <td>{!! $categoryInterior->description !!}</td>
            <td>{!! $categoryInterior->description_eng !!}</td>
            <td>{!! $categoryInterior->slug !!}</td>
            <td>
                {!! Form::open(['route' => ['categoryInteriors.destroy', $categoryInterior->id], 'method' => 'delete']) !!}
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{!! route('categoryInteriors.show', [$categoryInterior->id]) !!}" class="btn btn-sm btn-success"><i class="fa fa-eye"></i></a>
                                       <a href="{!! route('categoryInteriors.edit', [$categoryInterior->id]) !!}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                                       {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>