routes/web.php
<?php

use App\Http\Controllers\BuktiPembayaranController;
use App\Http\Controllers\CategoryInteriorController;
use App\Http\Controllers\DetailOrderController;
use App\Http\Controllers\InteriorGaleriController;
use App\Http\Controllers\InteriorHasProductController;
use App\Http\Controllers\KategoriProdukController;
use App\Http\Controllers\OrderFavoritesController;
use App\Http\Controllers\OrderProductController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RekeningController;
use App\Http\Controllers\StatusOrderController;
use App\Http\Controllers\WebsiteFrontEnd\WebsiteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Route::get('/', function () {
//   return view('welcome');
//});

Auth::routes(['verify' => true,
    'register' => true,
    'reset' => false,
]);

Route::get('interior_galery', function(){
    return view('website.interior_galery.index');
});

Route::get('interior_galery/detail', function(){
    return view('website.interior_galery.detail');
});
Route::get('interior_galery/detail2', function(){
    return view('website.interior_galery.detail2');
});
Route::get('interior_galery/detail3', function(){
    return view('website.interior_galery.detail3');
});
Route::get('interior_galery/detail4', function(){
    return view('website.interior_galery.detail4');
});
Route::get('interior_galery/detail5', function(){
    return view('website.interior_galery.detail5');
});

Route::get('interior_galery/detail6', function(){
    return view('website.interior_galery.detail6');
});

//Route::get('product_interior', function(){
//    return view('website.product_interior.index');
//});

Route::get('/refereshcaptcha', 'App\Http\Controllers\Auth\LoginController@refereshCaptcha');

//Custom Auth Routes
// Authentication Routes...

// Password Reset Routes...
/*$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');*/

Route::group(['middleware' => ['auth']], function () {

    Route::mediaLibrary();

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('roles', App\Http\Controllers\RoleController::class);

    Route::resource('permissions', App\Http\Controllers\PermissionController::class);

    Route::resource('users', App\Http\Controllers\UserController::class);

    Route::get('profil', [App\Http\Controllers\UserController::class, 'profil'])->name('profil');
    Route::get('editProfil/{id}', [App\Http\Controllers\UserController::class, 'editProfiles']);
    Route::patch('updateProfile/{id}', [App\Http\Controllers\UserController::class, 'updateProfile']);
    Route::resource('profiles', 'App\Http\Controllers\ProfileController');
    Route::get('editProfiles/{id}', [ProfileController::class,'editInfo']);

//
//    Route::resource('galeris', App\Http\Controllers\GaleriController::class);
//
//    Route::resource('pages', 'App\Http\Controllers\PageController');
//    Route::post('pagesIncrease/{id}', 'App\Http\Controllers\PageController@increase')->name('pagesIncrease');
//    Route::post('pagesDecrease/{id}', 'App\Http\Controllers\PageController@decrease')->name('pagesDecrease');
//
//    Route::resource('pageCategories', 'App\Http\Controllers\PageCategoryController');
//    Route::post('pageCategoriesIncrease/{id}', 'App\Http\Controllers\PageCategoryController@increase')->name('pageCategoriesIncrease');
//    Route::post('pageCategoriesDecrease/{id}', 'App\Http\Controllers\PageCategoryController@decrease')->name('pageCategoriesDecrease');
//
//    Route::resource('posts', 'App\Http\Controllers\PostController');
//
//    Route::resource('postCategories', 'App\Http\Controllers\PostCategoryController');
//    Route::post('postCategoriesIncrease/{id}', 'App\Http\Controllers\PostCategoryController@increase')->name('postCategoriesIncrease');
//    Route::post('postCategoriesDecrease/{id}', 'App\Http\Controllers\PostCategoryController@decrease')->name('postCategoriesDecrease');
    Route::resource('interiorGaleris', InteriorGaleriController::class);
    Route::resource('categoryInteriors', CategoryInteriorController::class);
    Route::resource('kategoriProduks', KategoriProdukController::class);
    Route::resource('produks', ProdukController::class);
    Route::post('produks_modal', [ProdukController::class, 'storeModal'])->name('produks_modal');
    Route::resource('interiorHasProducts', InteriorHasProductController::class);

    Route::resource('statusOrders', StatusOrderController::class);
    Route::resource('orderProducts', OrderProductController::class);
    Route::put('postOrder/{orderId}', [OrderProductController::class,'postOrder']);
    Route::get('updateStatus/{idOrder}', [OrderProductController::class,'updateStatus']);
    Route::resource('detailOrders', DetailOrderController::class);
    Route::resource('orderFavorites', OrderFavoritesController::class);
    Route::get('favoritesAdd/{interiorId}', [OrderFavoritesController::class,'favoriteAdd']);
    Route::get('order/{productId}', [OrderProductController::class,'insertOrder']);
    Route::resource('rekenings', RekeningController::class);
    Route::resource('buktiPembayarans', BuktiPembayaranController::class);
});

//----WEBSITE FRONT END
//Route::get('/', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'index'])->name('beranda');
//
////Detail Post
Route::get('post/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailPost'])->name('detail-post');
Route::get('page/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailPage'])->name('detail-page');
//
////Post Category
//Route::get('category/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'listPostByCategory'])->name('category-post');
//Route::get('sejarah', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'profilSejarah']);
//Route::get('profil-anggota-dprd', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'profilAnggotaDprd']);
//Route::get('post-utama', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'beritaUtama']);
//Route::get('post-utama/indeks', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'beritaSearch']);
//Route::get('anggota-dewan', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'anggotaDewan']);
//Route::get('alat-kelengkapan-dewan/{slugAkdCategory}', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'akdListPerson'])->name('alat-kelengkapan-dewan');
//Route::get('semua-anggota-dewan', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'listPersonDewan'])->name('semua-anggota-dewan');
//Route::get('semua-anggota-sekretariat', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'listPersonSekretariat'])->name('semua-anggota-sekretariat');
//Route::get('galeri-foto', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'galeriFoto'])->name('galeri-foto');
//Route::get('galeri-foto/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailGaleriFoto'])->name('detail-galeri-foto');
//Route::get('detail-person-dewan/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'detailPersonDewan'])->name('detail-person-dewan');
//Route::get('detail-person-sekretariat/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'detailPersonSekretariat'])->name('detail-person-sekretariat');
//Route::get('detail-instagram/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailInstagram'])->name('detail-instagram');
//Route::get('agenda-dprd', [WebsiteController::class,'agendaDprd'])->name('agenda-dprd');
//Route::get('agenda/agenda-detail/{slug}', [WebsiteController::class,'detailAgenda'])->name('agenda-detail');

Route::get('/',[WebsiteController::class,'index'])->name('beranda');
Route::get('interior',[WebsiteController::class,'interiorGaleri'])->name("interior-galeri");
Route::get('interior/{slug}',[WebsiteController::class,'detailInterior'])->name("interior-detail");
Route::get('product',[WebsiteController::class,'product'])->name('product-interior');
Route::get('checkout', [WebsiteController::class,'checkout']);
Route::get('orderStatus', [WebsiteController::class,'statusOrder'])->name('order_status');
Route::get('favorite', [WebsiteController::class,'favoriteInterior'])->name('favorite');

app/Models/OrderFavorites.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class OrderFavorites
 * @package App\Models
 * @version June 14, 2022, 1:38 am UTC
 *
 * @property \App\Models\User $users
 * @property \App\Models\Interior $interior
 * @property \App\Models\Product $product
 * @property integer $users_id
 * @property string $uuid
 * @property integer $product_id
 * @property integer $interior_id
 */
class OrderFavorites extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'order_favorites';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'users_id',
        'uuid',
        'product_id',
        'interior_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'users_id' => 'integer',
        'uuid' => 'string',
        'product_id' => 'integer',
        'interior_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
//        'users_id' => 'required',
//        'uuid' => 'nullable|string|max:255',
//        'created_at' => 'nullable',
//        'deleted_at' => 'nullable',
//        'updated_at' => 'nullable',
//        'product_id' => 'nullable',
//        'interior_id' => 'nullable'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function users()
    {
        return $this->belongsTo(\App\Models\User::class, 'users_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function interior()
    {
        return $this->belongsTo(\App\Models\InteriorGaleri::class, 'interior_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function product()
    {
        return $this->belongsTo(\App\Models\Produk::class, 'product_id');
    }
}

app/Http/Controllers/OrderFavoritesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateOrderFavoritesRequest;
use App\Http\Requests\UpdateOrderFavoritesRequest;
use App\Models\OrderFavorites;
use App\Repositories\OrderFavoritesRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use Auth;

class OrderFavoritesController extends AppBaseController
{
    /** @var  OrderFavoritesRepository */
    private $orderFavoritesRepository;

    public function __construct(OrderFavoritesRepository $orderFavoritesRepo)
    {
        $this->orderFavoritesRepository = $orderFavoritesRepo;
    }

    /**
     * Display a listing of the OrderFavorites.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $orderFavorites = $this->orderFavoritesRepository->all();

        return view('order_favorites.index')
            ->with('orderFavorites', $orderFavorites);
    }

    /**
     * Show the form for creating a new OrderFavorites.
     *
     * @return Response
     */
    public function create()
    {
        return view('order_favorites.create');
    }

    /**
     * Store a newly created OrderFavorites in storage.
     *
     * @param CreateOrderFavoritesRequest $request
     *
     * @return Response
     */
    public function store(CreateOrderFavoritesRequest $request)
    {
        $input = $request->all();

        $orderFavorites = $this->orderFavoritesRepository->create($input);

        Flash::success('Order Favorites saved successfully.');

        return redirect(route('orderFavorites.index'));
    }

    /**
     * Display the specified OrderFavorites.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $orderFavorites = $this->orderFavoritesRepository->find($id);

        if (empty($orderFavorites)) {
            Flash::error('Order Favorites not found');

            return redirect(route('orderFavorites.index'));
        }

        return view('order_favorites.show')->with('orderFavorites', $orderFavorites);
    }

    /**
     * Show the form for editing the specified OrderFavorites.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $orderFavorites = $this->orderFavoritesRepository->find($id);

        if (empty($orderFavorites)) {
            Flash::error('Order Favorites not found');

            return redirect(route('orderFavorites.index'));
        }

        return view('order_favorites.edit')->with('orderFavorites', $orderFavorites);
    }

    /**
     * Update the specified OrderFavorites in storage.
     *
     * @param int $id
     * @param UpdateOrderFavoritesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOrderFavoritesRequest $request)
    {
        $orderFavorites = $this->orderFavoritesRepository->find($id);

        if (empty($orderFavorites)) {
            Flash::error('Order Favorites not found');

            return redirect(route('orderFavorites.index'));
        }

        $orderFavorites = $this->orderFavoritesRepository->update($request->all(), $id);

        Flash::success('Order Favorites updated successfully.');

        return redirect(route('orderFavorites.index'));
    }

    /**
     * Remove the specified OrderFavorites from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $orderFavorites = $this->orderFavoritesRepository->find($id);

        if (empty($orderFavorites)) {
            Flash::error('Order Favorites not found');

            return redirect(route('orderFavorites.index'));
        }

        $this->orderFavoritesRepository->delete($id);

        Flash::success('Order Favorites deleted successfully.');

        return redirect()->back();
    }

    public function favoriteAdd($interiorId) {
        $favorite['users_id'] = Auth::id();
        $favorite['interior_id'] = $interiorId;
        OrderFavorites::updateOrCreate($favorite);
        return redirect()->back();
    }
}

resources/views/order_favorites/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-green p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="green font-medium-5">Input Order Favorites</span><br>
                                    <span style="margin-top: -5px">Membuat Order Favorites Baru</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                {!! Form::open(['route' => 'orderFavorites.store'], ['class' => 'form']) !!}
                                <div class="form-body">
                                    @include('order_favorites.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/order_favorites/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-indigo p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="indigo font-medium-5">Perubahan Order Favorites</span><br>
                                    <span style="margin-top: -5px">Melakukan Perubahan Order Favorites </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                {!! Form::model($orderFavorites, ['route' => ['orderFavorites.update', $orderFavorites->id], 'method' => 'patch']) !!}
                                <div class="form-body">
                                    @include('order_favorites.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/order_favorites/fields.blade.php
<!-- Users Id Field -->
<div class="form-group">
    {!! Form::label('users_id', 'Users Id:') !!}
    <div class="position-relative">
        {!! Form::number('users_id', null, ['class' => 'form-control']) !!}
    </div>
</div>


<!-- Uuid Field -->
<div class="form-group">
    {!! Form::label('uuid', 'Uuid:') !!}
    <div class="position-relative">
        {!! Form::text('uuid', null, ['class' => 'form-control']) !!}
    </div>
</div>


<!-- Product Id Field -->
<div class="form-group">
    {!! Form::label('product_id', 'Product Id:') !!}
    <div class="position-relative">
        {!! Form::number('product_id', null, ['class' => 'form-control']) !!}
    </div>
</div>


<!-- Interior Id Field -->
<div class="form-group">
    {!! Form::label('interior_id', 'Interior Id:') !!}
    <div class="position-relative">
        {!! Form::number('interior_id', null, ['class' => 'form-control']) !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Submit Field -->
<div class="form-actions center">
    <a href="{!! route('orderFavorites.index') !!}" class="btn btn-danger"> <i class="fa fa-close"></i> Batal</a>
    {!! Form::submit('Simpan', ['class' => 'btn btn-green mr-1']) !!}
</div>

resources/views/order_favorites/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                @include('flash::message')
                <div class="clearfix"></div>
                <div class="card">
                    <div class="border-left-pink border-left-6 box-shadow-1 rounded">
                        <div class="card-content ">
                            <div class="card-body card-dashboard">
                                <div class="row">
                                    <div class="col-10 media-body mb-2">
                                        <div class="content-header-left breadcrumb-new">
                                            <span class="content-header-title mb-0 d-inline-block font-medium-4"><b>Order Favorites</b></span>
                                            <div class="breadcrumbs-top d-inline-block">
                                                <div class="breadcrumb-wrapper">
                                                    @include('layouts.breadcrumb')
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-2 text-right">
                                        <a href="{!! route('orderFavorites.create') !!}" class="btn btn-sm btn-green">Tambah Data</a>
                                    </div>
                                </div>
                                @include('order_favorites.table')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/order_favorites/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-blue p-2 media-middle">
                                    <i class="fa fa-align-left font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="blue font-medium-5"> Order Favorites</span><br>
                                    <span style="margin-top: -5px">Detail Order Favorites</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form class="form form-horizontal">
                                    <div class="form-body">
                                        <h4 class="form-section">
                                            <a href="{!! route('orderFavorites.index') !!}" class="btn btn-icon danger btn-lg pl-0 ml-0"><i class="ft-arrow-left"></i> Kembali</a>
                                        </h4>
                                        @include('order_favorites.show_fields')
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/order_favorites/show_fields.blade.php
<!-- Sudah di modifikasi -->
<!-- Users Id Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('users_id', 'Users Id:') !!}
        </h5>
        {!! $orderFavorites->users_id !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Uuid Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('uuid', 'Uuid:') !!}
        </h5>
        {!! $orderFavorites->uuid !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Product Id Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('product_id', 'Product Id:') !!}
        </h5>
        {!! $orderFavorites->product_id !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Interior Id Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('interior_id', 'Interior Id:') !!}
        </h5>
        {!! $orderFavorites->interior_id !!}
    </div>
</div>

resources/views/order_favorites/table.blade.php
<!-- Sudah di modifikasi untuk Edit,Lihat,Hapus -->
<table class="table table-hover table-bordered table-striped default table-responsive">
    <colgroup>
        <col class="col-xs-1">
        <col class="col-xs-7">
    </colgroup>
    <thead>
    <tr>
        <th><code>#</code></th>
        <th>Users Id</th>
        <th>Uuid</th>
        <th>Product Id</th>
        <th>Interior Id</th>
        <th style="text-align: center">Action</th>
    </tr>
    </thead>
    <tbody>
    @php
        $no = 1;
    @endphp
    @foreach($orderFavorites as $orderFavorites)
        <tr>
            <td>{!! $no++ !!}</td>
            <td>{!! $orderFavorites->users_id !!}</td>
            <td>{!! $orderFavorites->uuid !!}</td>
            <td>{!! $orderFavorites->product_id !!}</td>
            <td>{!! $orderFavorites->interior_id !!}</td>
            <td>
                {!! Form::open(['route' => ['orderFavorites.destroy', $orderFavorites->id], 'method' => 'delete']) !!}
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{!! route('orderFavorites.show', [$orderFavorites->id]) !!}" class="btn btn-sm btn-success"><i class="fa fa-eye"></i></a>
                                       <a href="{!! route('orderFavorites.edit', [$orderFavorites->id]) !!}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                                       {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>